/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidadtres;

import funcion.matriz;
import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author Jorge Alvarado
 */
public class inversionMatricesParticionadas extends javax.swing.JFrame {

    /**
     * Creates new form InversionMatricesParticionadas
     */
    public inversionMatricesParticionadas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    DecimalFormat rd = new DecimalFormat("###.#####");

    int xMouse, yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAzul = new javax.swing.JPanel();
        panelDorado = new javax.swing.JPanel();
        textFieldDimension = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultados = new javax.swing.JTextArea();
        panelRetroceder = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAzul.setBackground(new java.awt.Color(0, 61, 121));

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        jPanel1.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 900));

        panelDorado.setBackground(new java.awt.Color(213, 159, 15));

        javax.swing.GroupLayout panelDoradoLayout = new javax.swing.GroupLayout(panelDorado);
        panelDorado.setLayout(panelDoradoLayout);
        panelDoradoLayout.setHorizontalGroup(
            panelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelDoradoLayout.setVerticalGroup(
            panelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        jPanel1.add(panelDorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 900));

        textFieldDimension.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        textFieldDimension.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDimension.setText("4");
        textFieldDimension.setBorder(null);
        textFieldDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDimensionActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldDimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, 10));

        panelValores.setBackground(new java.awt.Color(0, 134, 190));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar valores");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelValoresLayout = new javax.swing.GroupLayout(panelValores);
        panelValores.setLayout(panelValoresLayout);
        panelValoresLayout.setHorizontalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelValoresLayout.setVerticalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(panelValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 200, 50));

        textAreaResultados.setColumns(20);
        textAreaResultados.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textAreaResultados.setRows(5);
        jScrollPane1.setViewportView(textAreaResultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 800, 730));

        panelRetroceder.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRetrocederLayout = new javax.swing.GroupLayout(panelRetroceder);
        panelRetroceder.setLayout(panelRetrocederLayout);
        panelRetrocederLayout.setHorizontalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelRetrocederLayout.setVerticalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 40));

        panelSalir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setText("Inversion de matrices particionadas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 780, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel3.setText("Dimensión:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDimensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDimensionActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        matriz objetoMatriz = new matriz(); //

        int dimension = Integer.parseInt(textFieldDimension.getText());
        
        double[][] matrizA = new double[dimension][dimension];

        textAreaResultados.append("========= Nueva operación =========\n");

        if (dimension < 4) {
            textAreaResultados.append("La dimension de la matriz no pueder ser menor a 4\n");
        } else {
            matrizA = objetoMatriz.llenaMatriz(dimension);
            muestraMatriz(matrizA, dimension, dimension);
            dosParticiones(matrizA, dimension);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelValores.setBackground(sombra);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        Color original = new Color(0, 134, 190);
        panelValores.setBackground(original);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setVisible(false);
        metodosExactos abrir = new metodosExactos();
        abrir.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        panelRetroceder.setBackground(Color.gray);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        panelRetroceder.setBackground(Color.white);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        panelSalir.setBackground(Color.gray);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        panelSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inversionMatricesParticionadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inversionMatricesParticionadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inversionMatricesParticionadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inversionMatricesParticionadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inversionMatricesParticionadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelDorado;
    private javax.swing.JPanel panelRetroceder;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelValores;
    private javax.swing.JTextArea textAreaResultados;
    private javax.swing.JTextField textFieldDimension;
    // End of variables declaration//GEN-END:variables

    public void muestraMatriz(double[][] matriz, int renglon, int columna) {
        String auxiliar = "";
        for (int i = 0; i < renglon; i++) {
            auxiliar = " ";
            for (int j = 0; j < columna; j++) {
                auxiliar += "[ " + matriz[i][j] + " ]";
            }
            textAreaResultados.append(auxiliar + " \n");
        }
        textAreaResultados.append("\n");
    }

    public void muestraVector(double[] vector, int dimension) {
        String auxiliar = "";
        for (int i = 0; i < dimension; i++) {
            auxiliar += "| ";
            auxiliar += vector[i];
            auxiliar += " |\n";
        }
        textAreaResultados.append(auxiliar + "\n");
    }

    public void dosParticiones(double[][] matrizA, int dimension) {
        double[] vectorB = new double[dimension];

        matriz objetoMatriz = new matriz();

        if (objetoMatriz.determinanteMatriz(matrizA, dimension) == 0) {
            textAreaResultados.append("El determinante de la matriz es 0 por lo tanto no se puede seguir con el procedimiento");
        } else {

            textAreaResultados.append("El determinante de la matriz es: " + objetoMatriz.determinanteMatriz(matrizA, dimension) + "\n\n");

            vectorB = objetoMatriz.llenaVector(dimension);
            textAreaResultados.append("El vector resultado es: \n");
            muestraVector(vectorB, vectorB.length);

            double[][] A11 = new double[2][2];
            double[][] A12 = new double[2][dimension - 2];
            double[][] A21 = new double[dimension - 2][2];
            double[][] A22 = new double[dimension - 2][dimension - 2];

            double[][] b1 = new double[2][0];
            double[][] b2 = new double[dimension - 2][0];

            b1 = objetoMatriz.particionVector(vectorB,dimension,1);
            b2 = objetoMatriz.particionVector(vectorB,dimension,2);

            textAreaResultados.append("Vector B1: \n");
            muestraMatriz(b1, b1.length, b1[0].length);
            textAreaResultados.append("Vector B2: \n");
            muestraMatriz(b2, b2.length, b2[0].length);

//            b1 = particionVector(matrizB, 1);
            A11 = objetoMatriz.particionMatriz(matrizA,dimension,11);
            textAreaResultados.append("Matriz A11: \n");
            muestraMatriz(A11, A11.length, A11[0].length);

            A12 = objetoMatriz.particionMatriz(matrizA,dimension,12);
            textAreaResultados.append("Matriz A12: \n");
            muestraMatriz(A12, A12.length, A12[0].length);

            A21 = objetoMatriz.particionMatriz(matrizA,dimension,21);
            textAreaResultados.append("Matriz A21: \n");
            muestraMatriz(A21, A21.length, A21[0].length);

            A22 = objetoMatriz.particionMatriz(matrizA,dimension,22);
            textAreaResultados.append("Matriz A22: \n");
            muestraMatriz(A22, A22.length, A22[0].length);

            //System.out.println(A22.length);
            textAreaResultados.append("--- Operaciones para obtener la matriz D: ---\n\n");
            textAreaResultados.append("Matriz inversa de A22: \n");
            double[][] inversaA22 = new double[A22.length][A22[0].length];
            inversaA22 = objetoMatriz.matrizInversa(A22, A22.length);
            muestraMatriz(inversaA22, inversaA22.length, inversaA22[0].length);

            textAreaResultados.append("Matriz D = A12 * inversa A22: \n");
            double[][] matrizD = new double[A12.length][inversaA22[0].length];
            matrizD = objetoMatriz.multiplicacionMatrices(A12, inversaA22);
            muestraMatriz(matrizD, matrizD.length, matrizD[0].length);
            textAreaResultados.append("--- Fin ---\n\n");

            textAreaResultados.append("--- Operaciones para obtener la matriz C: ---\n\n");
            textAreaResultados.append("Matriz D * A21: \n");
            double[][] matrizDA21 = new double[matrizD.length][A21[0].length];
            matrizDA21 = objetoMatriz.multiplicacionMatrices(matrizD, A21);
            muestraMatriz(matrizDA21, matrizDA21.length, matrizDA21[0].length);

            textAreaResultados.append("Matriz C = A11 - D * A21 \n");
            double[][] matrizC = new double[matrizD.length][matrizD.length];
            matrizC = objetoMatriz.restaMatriz(A11, matrizDA21);
            muestraMatriz(matrizC, matrizC.length, matrizC.length);
            textAreaResultados.append("--- Fin ---\n\n");

            textAreaResultados.append("Matriz C inversa: \n");  //<-- Forma parte de la matriz final
            double[][] inversaC = new double[matrizC.length][matrizC[0].length];
            inversaC = objetoMatriz.matrizInversa(matrizC, matrizC.length);
            muestraMatriz(inversaC, inversaC.length, inversaC[0].length);

            textAreaResultados.append("--- Operaciones para obtener la matriz E: ---\n\n");
            textAreaResultados.append("Matriz E = inversaA22 * A21: \n");
            double[][] matrizE = new double[inversaA22.length][A21[0].length];
            matrizE = objetoMatriz.multiplicacionMatrices(inversaA22, A21);
            muestraMatriz(matrizE, matrizE.length, matrizE[0].length);
            textAreaResultados.append("--- Fin---\n\n");

            textAreaResultados.append("--- Operaciones para obtener la matriz F: ---\n\n");
            textAreaResultados.append("Matriz E * inversaC: \n");
            double[][] matrizECinversa = new double[matrizE.length][inversaC[0].length];
            matrizECinversa = objetoMatriz.multiplicacionMatrices(matrizE, inversaC);
            muestraMatriz(matrizECinversa, matrizECinversa.length, matrizECinversa[0].length);

            textAreaResultados.append("Matriz E * inversaC * D \n");
            double[][] matrizECinversaD = new double[matrizECinversa.length][matrizD[0].length];
            matrizECinversaD = objetoMatriz.multiplicacionMatrices(matrizECinversa, matrizD);
            muestraMatriz(matrizECinversaD, matrizECinversaD.length, matrizECinversaD[0].length);

            textAreaResultados.append("Matriz F = inversaA22 + E * inversaC * D: \n"); //<-- Forma parte de la matriz final
            double[][] matrizF = new double[matrizECinversaD.length][matrizECinversaD[0].length];
            matrizF = objetoMatriz.sumaMatriz(inversaA22, matrizECinversaD);
            muestraMatriz(matrizF, matrizF.length, matrizF[0].length);
            textAreaResultados.append("--- Fin ---\n");

            textAreaResultados.append("Matriz -inversaC  * D\n"); //<-- Forma parte de la matriz final
            double[][] menos1InversaC = new double[inversaC.length][inversaC[0].length];
            menos1InversaC = objetoMatriz.cambioDeSigno(inversaC);

            double[][] matrizMenoInversaCD = new double[menos1InversaC.length][matrizD[0].length];
            matrizMenoInversaCD = objetoMatriz.multiplicacionMatrices(menos1InversaC, matrizD);
            muestraMatriz(matrizMenoInversaCD, matrizMenoInversaCD.length, matrizMenoInversaCD[0].length);

            textAreaResultados.append("--- Operaciones para obtener la matriz X1: ---\n\n");
            textAreaResultados.append("Matriz D * b2\n");
            double[][] matrizDB2 = new double[matrizD.length][b2[0].length];
            matrizDB2 = objetoMatriz.multiplicacionMatrices(matrizD, b2);
            muestraMatriz(matrizDB2, matrizDB2.length, matrizDB2[0].length);

            textAreaResultados.append("Matriz b1 - D * b2: \n");
            double[][] matrizB1MenosDB2 = new double[matrizDB2.length][matrizDB2[0].length];
            matrizB1MenosDB2 = objetoMatriz.restaMatriz(b1, matrizDB2);
            muestraMatriz(matrizB1MenosDB2, matrizB1MenosDB2.length, matrizB1MenosDB2[0].length);

            textAreaResultados.append("Matriz X1 = inversaC (b1 - D*b2): \n");
            double[][] matrizX1 = new double[inversaC.length][matrizB1MenosDB2[0].length];
            matrizX1 = objetoMatriz.multiplicacionMatrices(inversaC, matrizB1MenosDB2);
            muestraMatriz(matrizX1, matrizX1.length, matrizX1[0].length);
            textAreaResultados.append("--- Fin ---\n\n");

            textAreaResultados.append("--- Operaciones para obtener la matriz X2: ---\n\n");
            textAreaResultados.append("Matriz F * b2: \n");
            double[][] matrizFB2 = new double[matrizF.length][b2[0].length];
            matrizFB2 = objetoMatriz.multiplicacionMatrices(matrizF, b2);
            muestraMatriz(matrizFB2, matrizFB2.length, matrizFB2[0].length);

            textAreaResultados.append("Matriz (-E * inversaC): \n"); //<-- Forma parte de la matriz final
            double[][] menosECinversa = new double[matrizECinversa.length][matrizECinversa[0].length];
            menosECinversa = objetoMatriz.cambioDeSigno(matrizECinversa);
            muestraMatriz(menosECinversa, menosECinversa.length, menosECinversa[0].length);

            textAreaResultados.append("Matriz -E * inversaC * b1: \n");
            double[][] matrizECinversaB1 = new double[matrizECinversa.length][b1[0].length];
            matrizECinversaB1 = objetoMatriz.multiplicacionMatrices(matrizECinversa, b1);
            muestraMatriz(matrizECinversaB1, matrizECinversaB1.length, matrizECinversaB1[0].length);

            textAreaResultados.append("Matriz X2 = -E * inversaC * b1 + F * b2: \n");
            double[][] matrizX2 = new double[matrizFB2.length][matrizFB2[0].length];
            double[][] menos1MatrizECB1 = new double[matrizECinversaB1.length][matrizECinversaB1[0].length];
            menos1MatrizECB1 = objetoMatriz.cambioDeSigno(matrizECinversaB1);
            matrizX2 = objetoMatriz.sumaMatriz(menos1MatrizECB1, matrizFB2);
            muestraMatriz(matrizX2, matrizX2.length, matrizX2[0].length);
            textAreaResultados.append("--- Fin ---\n");

            textAreaResultados.append("La matriz inversa es: \n");
            double[][] matrizInversa = new double[dimension][dimension];
            matrizInversa = objetoMatriz.armarMatriz(inversaC, matrizMenoInversaCD, menosECinversa, matrizF, dimension);
            muestraMatriz(matrizInversa, matrizInversa.length, matrizInversa[0].length);

            textAreaResultados.append("La solucion al sistemas es: \n");
            double[][] resultado = new double[dimension][0];
            resultado = objetoMatriz.armarVector(matrizX1, matrizX2, dimension);
            muestraMatriz(resultado, resultado.length, resultado[0].length);
        }

    }
}
