/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidadtres;

import java.awt.Color;
import portadas.PortadaUnidades;

/**
 *
 * @author Jorge Alvarado
 */
public class PortadaUnidadTres extends javax.swing.JFrame {

    /**
     * Creates new form PortadaUnidadTres
     */
    public PortadaUnidadTres() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    Color original = new Color(0, 134, 190);
    Color sombra = new Color(0, 134, 170);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        panelBackGround = new javax.swing.JPanel();
        panelAzul = new javax.swing.JPanel();
        panelDorado = new javax.swing.JPanel();
        panelExactos = new javax.swing.JPanel();
        labelExactos = new javax.swing.JLabel();
        panelJacobi = new javax.swing.JPanel();
        labelJacobi = new javax.swing.JLabel();
        panelGaussSeidel = new javax.swing.JPanel();
        labelGaussSeidel = new javax.swing.JLabel();
        panelRelajacion = new javax.swing.JPanel();
        labelRelajacion = new javax.swing.JLabel();
        panelCerrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRetroceder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        panelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAzul.setBackground(new java.awt.Color(0, 61, 121));

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        panelBackGround.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelDorado.setBackground(new java.awt.Color(213, 159, 15));

        javax.swing.GroupLayout panelDoradoLayout = new javax.swing.GroupLayout(panelDorado);
        panelDorado.setLayout(panelDoradoLayout);
        panelDoradoLayout.setHorizontalGroup(
            panelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelDoradoLayout.setVerticalGroup(
            panelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        panelBackGround.add(panelDorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        panelExactos.setBackground(new java.awt.Color(0, 134, 190));

        labelExactos.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelExactos.setForeground(new java.awt.Color(255, 255, 255));
        labelExactos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExactos.setText("Métodos exactos ");
        labelExactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExactosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExactosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExactosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelExactosLayout = new javax.swing.GroupLayout(panelExactos);
        panelExactos.setLayout(panelExactosLayout);
        panelExactosLayout.setHorizontalGroup(
            panelExactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelExactos, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        panelExactosLayout.setVerticalGroup(
            panelExactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelExactos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelBackGround.add(panelExactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        panelJacobi.setBackground(new java.awt.Color(0, 134, 190));

        labelJacobi.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelJacobi.setForeground(new java.awt.Color(255, 255, 255));
        labelJacobi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJacobi.setText("Método de Jacobi");
        labelJacobi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelJacobi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelJacobiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelJacobiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelJacobiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelJacobiLayout = new javax.swing.GroupLayout(panelJacobi);
        panelJacobi.setLayout(panelJacobiLayout);
        panelJacobiLayout.setHorizontalGroup(
            panelJacobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelJacobi, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        panelJacobiLayout.setVerticalGroup(
            panelJacobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelJacobi, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelBackGround.add(panelJacobi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        panelGaussSeidel.setBackground(new java.awt.Color(0, 134, 190));

        labelGaussSeidel.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelGaussSeidel.setForeground(new java.awt.Color(255, 255, 255));
        labelGaussSeidel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGaussSeidel.setText("Método Gauss-Seidel");
        labelGaussSeidel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelGaussSeidel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelGaussSeidelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelGaussSeidelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelGaussSeidelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGaussSeidelLayout = new javax.swing.GroupLayout(panelGaussSeidel);
        panelGaussSeidel.setLayout(panelGaussSeidelLayout);
        panelGaussSeidelLayout.setHorizontalGroup(
            panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGaussSeidel, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        panelGaussSeidelLayout.setVerticalGroup(
            panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGaussSeidel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelBackGround.add(panelGaussSeidel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 643, -1));

        panelRelajacion.setBackground(new java.awt.Color(0, 134, 190));

        labelRelajacion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelRelajacion.setForeground(new java.awt.Color(255, 255, 255));
        labelRelajacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelajacion.setText("Método de relajación");
        labelRelajacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRelajacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRelajacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRelajacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRelajacionLayout = new javax.swing.GroupLayout(panelRelajacion);
        panelRelajacion.setLayout(panelRelajacionLayout);
        panelRelajacionLayout.setHorizontalGroup(
            panelRelajacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRelajacion, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        panelRelajacionLayout.setVerticalGroup(
            panelRelajacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRelajacion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelBackGround.add(panelRelajacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 643, -1));

        panelCerrar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarLayout = new javax.swing.GroupLayout(panelCerrar);
        panelCerrar.setLayout(panelCerrarLayout);
        panelCerrarLayout.setHorizontalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelCerrarLayout.setVerticalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(panelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        panelRetroceder.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRetrocederLayout = new javax.swing.GroupLayout(panelRetroceder);
        panelRetroceder.setLayout(panelRetrocederLayout);
        panelRetrocederLayout.setHorizontalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelRetrocederLayout.setVerticalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(panelRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/b_fesalogo.png"))); // NOI18N
        panelBackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExactosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExactosMouseEntered
        panelExactos.setBackground(sombra);
    }//GEN-LAST:event_labelExactosMouseEntered

    private void labelExactosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExactosMouseExited

        panelExactos.setBackground(original);
    }//GEN-LAST:event_labelExactosMouseExited

    private void labelExactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExactosMouseClicked
        this.setVisible(false);
        metodosExactos abrir = new metodosExactos();
        abrir.setVisible(true);
    }//GEN-LAST:event_labelExactosMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        PortadaUnidades abrir = new PortadaUnidades();
        abrir.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        panelRetroceder.setBackground(Color.gray);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        panelCerrar.setBackground(Color.gray);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        panelRetroceder.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        panelCerrar.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void labelJacobiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJacobiMouseEntered
        panelJacobi.setBackground(sombra);
    }//GEN-LAST:event_labelJacobiMouseEntered

    private void labelJacobiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJacobiMouseExited
        panelJacobi.setBackground(original);
    }//GEN-LAST:event_labelJacobiMouseExited

    private void labelJacobiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelJacobiMouseClicked
        Jacobi abrir = new Jacobi();
        this.setVisible(false);
        abrir.setVisible(true);
    }//GEN-LAST:event_labelJacobiMouseClicked

    private void labelGaussSeidelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGaussSeidelMouseEntered
        panelGaussSeidel.setBackground(sombra);        // TODO add your handling code here:
    }//GEN-LAST:event_labelGaussSeidelMouseEntered

    private void labelGaussSeidelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGaussSeidelMouseExited
        panelGaussSeidel.setBackground(original);
        // TODO add your handling code here:
    }//GEN-LAST:event_labelGaussSeidelMouseExited

    private void labelGaussSeidelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGaussSeidelMouseClicked
        GausSeidel abrir = new GausSeidel();
        this.setVisible(false);
        abrir.setVisible(true);
    }//GEN-LAST:event_labelGaussSeidelMouseClicked

    private void labelRelajacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRelajacionMouseEntered
        panelRelajacion.setBackground(sombra);
    }//GEN-LAST:event_labelRelajacionMouseEntered

    private void labelRelajacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRelajacionMouseExited
        panelRelajacion.setBackground(original);        // TODO add your handling code here:
    }//GEN-LAST:event_labelRelajacionMouseExited

    private void labelRelajacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRelajacionMouseClicked
        this.setVisible(false);
        metodoRelajacion abrir = new metodoRelajacion();
        abrir.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_labelRelajacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortadaUnidadTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortadaUnidadTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortadaUnidadTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortadaUnidadTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortadaUnidadTres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelExactos;
    private javax.swing.JLabel labelGaussSeidel;
    private javax.swing.JLabel labelJacobi;
    private javax.swing.JLabel labelRelajacion;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel panelDorado;
    private javax.swing.JPanel panelExactos;
    private javax.swing.JPanel panelGaussSeidel;
    private javax.swing.JPanel panelJacobi;
    private javax.swing.JPanel panelRelajacion;
    private javax.swing.JPanel panelRetroceder;
    // End of variables declaration//GEN-END:variables
}
