/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidaddos;

import funcion.evaluarFunciones;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Alvarado
 */
public class MetodoSecante extends javax.swing.JFrame {

    /**
     * Creates new form MetodoSecante
     */
    

    public MetodoSecante() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    int xMouse, yMouse;
    DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackGround = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFuncion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        textXnMenos1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        textXn = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        textError = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        textIteraciones = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        panelEvaluar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelInformacion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultado = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        labelFuncion = new javax.swing.JLabel();
        labelRaiz = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelRetroceder = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelLimpiar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        panelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 61, 121));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 890));

        jPanel3.setBackground(new java.awt.Color(213, 159, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 890));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel1.setText("FUNCIÓN");
        panelBackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 62, -1, -1));

        textFuncion.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textFuncion.setForeground(new java.awt.Color(204, 204, 204));
        textFuncion.setText("Ingrese su función aquí");
        textFuncion.setBorder(null);
        textFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFuncionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFuncionMousePressed(evt);
            }
        });
        panelBackGround.add(textFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 92, 500, 30));
        panelBackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 122, 500, 10));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel2.setText("Xn-1");
        panelBackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 142, -1, -1));

        textXnMenos1.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textXnMenos1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textXnMenos1.setText("0");
        textXnMenos1.setBorder(null);
        panelBackGround.add(textXnMenos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 142, 100, 20));
        panelBackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 162, 100, 10));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel3.setText("Xn");
        panelBackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        textXn.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textXn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textXn.setText("1");
        textXn.setBorder(null);
        panelBackGround.add(textXn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, 20));
        panelBackGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 100, 10));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel4.setText("Error");
        panelBackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        textError.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textError.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textError.setText("0.0001");
        textError.setBorder(null);
        panelBackGround.add(textError, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 100, 20));
        panelBackGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 100, 10));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel5.setText("Iteraciones");
        panelBackGround.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        textIteraciones.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textIteraciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textIteraciones.setText("100");
        textIteraciones.setBorder(null);
        panelBackGround.add(textIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 100, 20));
        panelBackGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 100, 10));

        panelEvaluar.setBackground(new java.awt.Color(0, 134, 190));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Evaluar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEvaluarLayout = new javax.swing.GroupLayout(panelEvaluar);
        panelEvaluar.setLayout(panelEvaluarLayout);
        panelEvaluarLayout.setHorizontalGroup(
            panelEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        panelEvaluarLayout.setVerticalGroup(
            panelEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBackGround.add(panelEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 280, -1));

        panelInformacion.setBackground(new java.awt.Color(0, 134, 190));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Teoria");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBackGround.add(panelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 280, -1));

        tablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "Xn-1", "Xn", "f(Xn)", "f(Xn-1)", "Xn+1", "f(Xn+1)", "|f(Xn+1)|<error"
            }
        ));
        jScrollPane1.setViewportView(tablaResultado);

        panelBackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 858, -1));
        panelBackGround.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 860, 10));

        labelFuncion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelFuncion.setText("f(x) = ");
        panelBackGround.add(labelFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, -1, -1));

        labelRaiz.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelRaiz.setText("La raiz de f(x) es = ");
        panelBackGround.add(labelRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 830, -1, -1));

        panelSalir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("x");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, -1, -1));

        panelRetroceder.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRetrocederLayout = new javax.swing.GroupLayout(panelRetroceder);
        panelRetroceder.setLayout(panelRetrocederLayout);
        panelRetrocederLayout.setHorizontalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelRetrocederLayout.setVerticalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(panelRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jLabel8.setText("Método de la secante");
        panelBackGround.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 38, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 0, -1, 31));

        panelLimpiar.setBackground(new java.awt.Color(0, 134, 190));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Limpiar");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLimpiarLayout = new javax.swing.GroupLayout(panelLimpiar);
        panelLimpiar.setLayout(panelLimpiarLayout);
        panelLimpiarLayout.setHorizontalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        panelLimpiarLayout.setVerticalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBackGround.add(panelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 280, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelEvaluar.setBackground(sombra);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        Color original = new Color(0, 134, 190);
        panelEvaluar.setBackground(original);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelInformacion.setBackground(sombra);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        Color original = new Color(0, 134, 190);
        panelInformacion.setBackground(original);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        panelSalir.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        panelSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        panelRetroceder.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        panelRetroceder.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setVisible(false);
        portadaUnidadDos abrir = new portadaUnidadDos();
        abrir.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        String funcion = textFuncion.getText();
        evaluarFunciones Funcion = new evaluarFunciones();

        Funcion.setFuncion(funcion);
        modelo = (DefaultTableModel) tablaResultado.getModel();

        if (Funcion.contieneX() && !funcion.equals("")) {
            metodoSecante(funcion);
        } else {
            JOptionPane.showMessageDialog(null, "Introduzca una funcion valida \n "
                    + "(El campo de la funcion esta vacio o la funcion no es valida) \n Las funciones validas son: \n "
                    + "polinomios, trigonometricas, racionales, radicales", "ERROR 2", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void textFuncionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFuncionMouseClicked

    }//GEN-LAST:event_textFuncionMouseClicked

    private void textFuncionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFuncionMousePressed
        textFuncion.setText("");
        textFuncion.setForeground(Color.black);
    }//GEN-LAST:event_textFuncionMousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse); // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Color sombra = new Color(204,204,204);
        textFuncion.setForeground(sombra);
        textFuncion.setText("Ingrese su función aquí");
        textError.setText("0.0001");
        textXnMenos1.setText("0");
        textXn.setText("1");
        limpiarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelLimpiar.setBackground(sombra);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        Color original = new Color(0, 134, 190);
        panelLimpiar.setBackground(original);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoSecante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelFuncion;
    private javax.swing.JLabel labelRaiz;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelEvaluar;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelLimpiar;
    private javax.swing.JPanel panelRetroceder;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JTable tablaResultado;
    private javax.swing.JTextField textError;
    private javax.swing.JTextField textFuncion;
    private javax.swing.JTextField textIteraciones;
    private javax.swing.JTextField textXn;
    private javax.swing.JTextField textXnMenos1;
    // End of variables declaration//GEN-END:variables

        public void limpiarTabla() {
        tablaResultado.setModel(new DefaultTableModel(new Object[][]{},
                new String[]{"n", "Xn-1", "Xn", "f(Xn)", "f(Xn-1)", "Xn+1", "f(Xn+1)", "|f(Xn+1)|<error"}) {
        });
    }
    
    public void metodoSecante(String funcion) {

        double xnMenos1 = Double.parseDouble(textXnMenos1.getText());
        double xn = Double.parseDouble(textXn.getText());
        double error = Double.parseDouble(textError.getText());
        double iteraciones = Double.parseDouble(textIteraciones.getText());

        double xnMas1 = 0;

        evaluarFunciones Funcion = new evaluarFunciones();
        Funcion.setFuncion(funcion);

        double funcionXnMenos1 = Funcion.evaluar(xnMenos1);
        double funcionXn = Funcion.evaluar(xn);

        int n = 0;

        if (Math.abs(funcionXnMenos1) < error) {
            JOptionPane.showMessageDialog(null, "La raiz se encuentra en el punto Xn-1");
            //labelRaiz.setText("El valor de la raiz es: " + a);
        } else if (Math.abs(funcionXn) < error) {
            JOptionPane.showMessageDialog(null, "La raiz se encuentra en el intervalo Xn");
            //labelRaiz.setText("El valor de la raiz es: " + a);
        } else {
            
            do{
                xnMas1 = xn -((Funcion.evaluar(xn))*(xn - xnMenos1)/(Funcion.evaluar(xn)-Funcion.evaluar(xnMenos1)));
                
                modelo.addRow(new Object[]{n,xnMenos1,xn,Funcion.evaluar(xn),
                Funcion.evaluar(xnMenos1),xnMas1,Funcion.evaluar(xnMas1),
                    menorError(error, Funcion.evaluar(xnMas1))});
            
                xnMenos1=xn;
                xn=xnMas1;
                n++;
                
                labelFuncion.setText("f(x) = " + funcion);
                labelRaiz.setText("La raíz de f(x) es = " + xnMas1);
            
            }while(Math.abs(Funcion.evaluar(xnMas1))>error && n <= iteraciones);
            
        }

    }

    public boolean menorError(double error, double funcionX) {
        if (Math.abs(funcionX) < error) {
            return true;
        }
        return false;
    }

}
