/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidaddos;

import java.awt.Color;
import funcion.evaluarFunciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import informacion.*;

/**
 *
 * @author Jorge Alvarado
 */
public class MetodoNewton extends javax.swing.JFrame {

    /**
     * Creates new form MetodoNewton
     */
    public MetodoNewton() {
        initComponents();
        setLocationRelativeTo(null);
    }

    int xMouse, yMouse;

    DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackGround = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFuncion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        textPuntoInicio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        textError = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        textIteraciones = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        panelEvaluar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelTeoria = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        labelFuncion = new javax.swing.JLabel();
        labelFuncionDerivada = new javax.swing.JLabel();
        labelRaiz = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelRetroceder = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelLimpiar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelBackGround.setBackground(new java.awt.Color(255, 255, 255));
        panelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 61, 121));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 890));

        jPanel3.setBackground(new java.awt.Color(213, 159, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 890));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel1.setText("FUNCIÓN");
        panelBackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        textFuncion.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textFuncion.setForeground(new java.awt.Color(204, 204, 204));
        textFuncion.setText("Ingrese su función aquí");
        textFuncion.setBorder(null);
        textFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFuncionMousePressed(evt);
            }
        });
        panelBackGround.add(textFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 500, 30));
        panelBackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 136, 500, 11));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel2.setText("Punto inicial");
        panelBackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        textPuntoInicio.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textPuntoInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPuntoInicio.setBorder(null);
        panelBackGround.add(textPuntoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 20));
        panelBackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, 10));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel3.setText("Error");
        panelBackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        textError.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textError.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textError.setText("0.0001");
        textError.setBorder(null);
        panelBackGround.add(textError, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 20));
        panelBackGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 10));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel4.setText("Iteraciones");
        panelBackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        textIteraciones.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        textIteraciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textIteraciones.setText("100");
        textIteraciones.setBorder(null);
        textIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIteracionesActionPerformed(evt);
            }
        });
        panelBackGround.add(textIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 100, 20));
        panelBackGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 100, 13));

        panelEvaluar.setBackground(new java.awt.Color(0, 134, 190));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Evaluar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEvaluarLayout = new javax.swing.GroupLayout(panelEvaluar);
        panelEvaluar.setLayout(panelEvaluarLayout);
        panelEvaluarLayout.setHorizontalGroup(
            panelEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEvaluarLayout.setVerticalGroup(
            panelEvaluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBackGround.add(panelEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 280, -1));

        panelTeoria.setBackground(new java.awt.Color(0, 134, 190));
        panelTeoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Teoria");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelTeoriaLayout = new javax.swing.GroupLayout(panelTeoria);
        panelTeoria.setLayout(panelTeoriaLayout);
        panelTeoriaLayout.setHorizontalGroup(
            panelTeoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTeoriaLayout.setVerticalGroup(
            panelTeoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBackGround.add(panelTeoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 280, -1));
        panelBackGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 860, 10));

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "n", "Xn", "f(Xn)", "f'(Xn)", "Xn+1", "f(Xn+1)", "|f(Xn+1)|<error"
            }
        ));
        jScrollPane1.setViewportView(tablaResultados);

        panelBackGround.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 316, 860, -1));

        labelFuncion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelFuncion.setText("f(x) =");
        panelBackGround.add(labelFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, -1, -1));

        labelFuncionDerivada.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelFuncionDerivada.setText("f'(x) =");
        panelBackGround.add(labelFuncionDerivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 810, -1, -1));

        labelRaiz.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelRaiz.setText("La raíz de f(x) es =");
        panelBackGround.add(labelRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 850, -1, -1));

        panelSalir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 40, -1));

        panelRetroceder.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRetrocederLayout = new javax.swing.GroupLayout(panelRetroceder);
        panelRetroceder.setLayout(panelRetrocederLayout);
        panelRetrocederLayout.setHorizontalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRetrocederLayout.setVerticalGroup(
            panelRetrocederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(panelRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 40, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jLabel9.setText("Método de Newton");
        panelBackGround.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 37, -1, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        panelLimpiar.setBackground(new java.awt.Color(0, 134, 190));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Limpiar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLimpiarLayout = new javax.swing.GroupLayout(panelLimpiar);
        panelLimpiar.setLayout(panelLimpiarLayout);
        panelLimpiarLayout.setHorizontalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLimpiarLayout.setVerticalGroup(
            panelLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBackGround.add(panelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 280, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelBackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 880, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelEvaluar.setBackground(sombra);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        Color original = new Color(0, 134, 190);
        panelEvaluar.setBackground(original);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        String funcion = textFuncion.getText();

        limpiarTabla();
        modelo = (DefaultTableModel) tablaResultados.getModel();
        evaluarFunciones Funcion = new evaluarFunciones();
        Funcion.setFuncion(funcion);

        if (!Funcion.equals("") && Funcion.contieneX()) {
            metodoNewton(funcion);
        } else {
            JOptionPane.showMessageDialog(null, "Introduzca una funcion valida \n "
                    + "(El campo de la funcion esta vacio o la funcion no es valida) \n Las funciones validas son: \n "
                    + "polinomios, trigonometricas, racionales, radicales", "ERROR 2", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void textFuncionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFuncionMousePressed
        textFuncion.setText("");
        textFuncion.setForeground(Color.BLACK);
    }//GEN-LAST:event_textFuncionMousePressed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        panelSalir.setBackground(Color.gray);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        panelSalir.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        panelRetroceder.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        panelRetroceder.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
        portadaUnidadDos abrir = new portadaUnidadDos();
        abrir.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void textIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIteracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIteracionesActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelTeoria.setBackground(sombra);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        Color original = new Color(0, 134, 190);
        panelTeoria.setBackground(original);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        informacionNewton abrir = new informacionNewton();
        abrir.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Color sombra = new Color(204, 204, 204);
        textFuncion.setForeground(sombra);
        textFuncion.setText("Ingrese su función aquí");
        textError.setText("0.0001");
        textPuntoInicio.setText("0");
        limpiarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        Color original = new Color(0, 134, 190);
        panelLimpiar.setBackground(original);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        Color sombra = new Color(0, 134, 170);
        panelLimpiar.setBackground(sombra);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();      // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoNewton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelFuncion;
    private javax.swing.JLabel labelFuncionDerivada;
    private javax.swing.JLabel labelRaiz;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelEvaluar;
    private javax.swing.JPanel panelLimpiar;
    private javax.swing.JPanel panelRetroceder;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelTeoria;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JTextField textError;
    private javax.swing.JTextField textFuncion;
    private javax.swing.JTextField textIteraciones;
    private javax.swing.JTextField textPuntoInicio;
    // End of variables declaration//GEN-END:variables

    public void limpiarTabla() {
        tablaResultados.setModel(new DefaultTableModel(new Object[][]{},
                new String[]{"n", "Xn", "f(Xn)", "f'(xn)", "Xn+1", "f(Xn+1)", "|f(Xn+1)|<error"}) {
        });
    }

    public void metodoNewton(String funcion) {

        double puntoInicio = Double.parseDouble(textPuntoInicio.getText());
        double error = Double.parseDouble(textError.getText());
        double iteraciones = Double.parseDouble(textIteraciones.getText());

        int n = 0;

        evaluarFunciones Funcion = new evaluarFunciones();
        Funcion.setFuncion(funcion);

        String derivada = Funcion.derivar();
        evaluarFunciones FuncionDev = new evaluarFunciones();
        FuncionDev.setFuncion(derivada);

        if (FuncionDev.evaluar(puntoInicio) != 0) {

            while (Math.abs(Funcion.evaluar(puntoInicio)) > error && n < iteraciones) {

                double siguientePunto = 0;

                siguientePunto = puntoInicio - (Funcion.evaluar(puntoInicio) / FuncionDev.evaluar(puntoInicio));

                modelo.addRow(new Object[]{n, puntoInicio, Funcion.evaluar(puntoInicio),
                    FuncionDev.evaluar(puntoInicio), siguientePunto, Funcion.evaluar(siguientePunto),
                    menorError(error, Funcion.evaluar(siguientePunto))});

                n++;
                puntoInicio = siguientePunto;

                labelFuncion.setText("f(x) = " + Funcion.getFuncion());
                labelFuncionDerivada.setText("f'(x) = " + FuncionDev.getFuncion());
                labelRaiz.setText("La raíz de f(x) es = " + siguientePunto);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya que la derivada evaluada en el punto es 0 el metodo es indeterminado"
                    + "Ingresa otro punto inicial", "Error 1.0", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean menorError(double error, double funcionXn1) {
        if (Math.abs(funcionXn1) < error) {
            return true;
        }
        return false;
    }

}
